services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL_Server
    ports:
      - 1434:1433
    environment:
      - MSSQL_SA_PASSWORD=HaSsi3l.02
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    
    volumes:
      - sql_server_data:/var/opt/mssql
volumes:
  sql_server_data:  storeapi:
    image: storeapi
    build:
      context: .
      dockerfile: StoreAPI/Dockerfile

